# Generated by Django 4.1.3 on 2022-11-20 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_analizado'),
    ]

    operations = [
        migrations.DeleteModel(
            name='analizado',
        ),
    ]
