# Generated by Django 4.1.3 on 2022-11-20 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_delete_analizado'),
    ]

    operations = [
        migrations.CreateModel(
            name='analizado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datolun', models.IntegerField()),
                ('datomar', models.IntegerField()),
                ('datomie', models.IntegerField()),
                ('datojue', models.IntegerField()),
                ('datovie', models.IntegerField()),
            ],
        ),
    ]
