# Generated by Django 4.1.3 on 2022-11-20 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0004_analizado'),
    ]

    operations = [
        migrations.CreateModel(
            name='submana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.ManyToManyField(to='Home.choice')),
            ],
        ),
    ]
