# Generated by Django 4.1.3 on 2022-11-20 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0005_submana'),
    ]

    operations = [
        migrations.DeleteModel(
            name='submana',
        ),
    ]
