# Generated by Django 4.1.3 on 2022-11-20 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0011_mezcla'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mezcla',
        ),
    ]
