# Generated by Django 4.1.3 on 2022-11-20 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0012_delete_mezcla'),
    ]

    operations = [
        migrations.DeleteModel(
            name='analizado',
        ),
    ]
