# Generated by Django 4.1.3 on 2022-11-20 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0013_delete_analizado'),
    ]

    operations = [
        migrations.CreateModel(
            name='datosnuevos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datoimp', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Home.submission')),
            ],
        ),
    ]
