# Generated by Django 4.1.3 on 2022-11-20 19:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0015_rename_datoimp_datosnuevos_submission'),
    ]

    operations = [
        migrations.AddField(
            model_name='datosnuevos',
            name='idkdato',
            field=models.ManyToManyField(to='Home.submission'),
        ),
        migrations.AlterField(
            model_name='datosnuevos',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Home.choice'),
        ),
    ]
