# Generated by Django 4.1.3 on 2022-11-20 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0016_datosnuevos_idkdato_alter_datosnuevos_submission'),
    ]

    operations = [
        migrations.DeleteModel(
            name='datosnuevos',
        ),
    ]
