# Generated by Django 4.1.3 on 2022-11-21 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0018_encuesta_pregunta_respuesta_respuesta_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='respuesta_usuario',
            name='encuesta',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Home.encuesta'),
            preserve_default=False,
        ),
    ]
