# Generated by Django 4.1.3 on 2022-11-21 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0019_respuesta_usuario_encuesta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encuesta',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
