# Generated by Django 4.1.3 on 2022-11-21 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0023_remove_encuesta_usuario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pregunta',
            old_name='texto',
            new_name='text',
        ),
    ]
