# Generated by Django 4.1.3 on 2022-11-21 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0025_rename_respuesta_respuesta_usuario_contesta_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='respuesta_usuario',
            name='usuario',
        ),
        migrations.AlterField(
            model_name='respuesta_usuario',
            name='contesta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Home.respuesta'),
        ),
    ]
