# Generated by Django 4.1.3 on 2022-11-21 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0026_remove_respuesta_usuario_usuario_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='datos_importantes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datocont', models.ManyToManyField(to='Home.respuesta')),
                ('prueba', models.ManyToManyField(to='Home.respuesta_usuario')),
            ],
        ),
    ]
