# Generated by Django 4.1.3 on 2022-11-21 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0027_datos_importantes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datos_importantes',
            name='prueba',
        ),
    ]
