# Generated by Django 4.1.3 on 2022-11-21 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0028_remove_datos_importantes_prueba'),
    ]

    operations = [
        migrations.AddField(
            model_name='datos_importantes',
            name='Encuesta',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='Home.encuesta'),
            preserve_default=False,
        ),
    ]
