# Generated by Django 4.1.3 on 2022-11-21 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0033_rename_answer_datoimp_ans_submission_answer'),
    ]

    operations = [
        migrations.CreateModel(
            name='estadocasino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(max_length=255)),
            ],
        ),
    ]
