# Generated by Django 4.1.3 on 2022-11-21 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0034_estadocasino'),
    ]

    operations = [
        migrations.DeleteModel(
            name='datoimp',
        ),
    ]
