# Generated by Django 4.1.3 on 2022-11-22 01:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0035_delete_datoimp'),
    ]

    operations = [
        migrations.CreateModel(
            name='datoimp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('envia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Home.submission')),
                ('importante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Home.choice')),
            ],
        ),
    ]
