# Generated by Django 4.1.3 on 2022-11-22 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0036_datoimp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datoimp',
            name='envia',
        ),
        migrations.AddField(
            model_name='datoimp',
            name='envia',
            field=models.ManyToManyField(to='Home.submission'),
        ),
    ]
